[build]

  command = "./vendor/bin/jigsaw build production"
  publish = "build_production"

[build.environment]

  PHP_VERSION = "7.2"

[[redirects]]
  from = "https://staticpress-comingsoon.netlify.com"
  to = "https://comingsoon-demo.staticpress.io"
  status = 301
  force = true